<?
$aMenuLinks = Array(
	Array(
		"Имплантация", 
		"/uslugi/implantaciya-zubov-v-moskve/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Синус-лифтинг", 
		"/uslugi/sinus-lifting/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Ортодонтия", 
		"/uslugi/ortodontiya/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Детская стоматология", 
		"/uslugi/detskaya-stomatologiya/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Парадонтология", 
		"/uslugi/paradontologiya/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Травмы", 
		"/uslugi/travmy-zubov/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Хирургия", 
		"/uslugi/khirurgiya-zubov/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Протезирование", 
		"/uslugi/protezirovanie-zubov/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Эндодонтия", 
		"/uslugi/endodontiya/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Реставрации", 
		"/uslugi/restavratsii-zubov/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Виниры", 
		"/uslugi/viniry/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Костная пластика", 
		"/uslugi/kostnaya-plastika/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Импланты", 
		"/uslugi/implanty/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Отбеливание Brite Smile", 
		"/uslugi/otbelivanie-brite-smile/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Гигиена, профилактика и чистка зубов", 
		"/uslugi/gigiena-profilaktika-i-chistka-zubov/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Протезирование керамическими коронками", 
		"/uslugi/protezirovanie-keramicheskimi-koronkami/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Ортогнатическая хирургия", 
		"/uslugi/ortognaticheskaya-khirurgiya/", 
		Array(), 
		Array(), 
		"" 
	)
);
?>