<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("title", "Restorations in American dental center Moscow");
require($_SERVER["DOCUMENT_ROOT"].SITE_TEMPLATE_PATH."/fixedwidth-header.php");
$APPLICATION->SetTitle("Restorations American dental center");
$APPLICATION->SetPageProperty("description", "Restoration and restoration of teeth at the American Dental Implantation Center. Restoration of the natural structure and functionality of teeth");
?><p>Caries (decay) is generally speaking a hole in the hard tissues of the tooth which is generated by bacteria form the plaque. It goes deep into the tooth and may cause cause severe pain when the tooth nerve becomes infected if left untreated. It is a matter of great importance that you see your dentist every half a year to observe your teeth and to make fillings if you have caries.</p>

<p>Also teeth can be damaged traumatically. In this case small pieces of tooth ussually came out and the tooth inside tissues become naked and available for bacteria. If you break the front teeth it also causes cosmetic dafects. Sometimes the tooth root fractures which can't be seen without proper dental ckeck-up and in time you may loose such tooth. That's why whenever you have your tooth broken you should restore it.</p>

<p>Fillings are made of materials which immitate natural tooth tissues. It immitates it in properties and colour. Also it guards your teeth from bacteria and therefore save your health.</p>

<p>The latest restorative materials are light-cured composite materials. They are highly esthetical, most close to the natural teeth tissues, have highest preventive ability and no toxic effect on the tooth structures. Once you have you tooth filled with composite you may never ever remember you have it.</p>

<?require($_SERVER["DOCUMENT_ROOT"].SITE_TEMPLATE_PATH."/fixedwidth-footer.php"); require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>